apiVersion: v1
kind: Namespace
metadata:
  name: crocodille-erp

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: crocodille-erp
  namespace: crocodille-erp
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: crocodille-erp
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: crocodille-erp
    spec:
      imagePullSecrets:
      - name: ghcr-secret
      containers:
        - image: ghcr.io/radixal-sro/crocodille-erp:latest
          imagePullPolicy: Always
          name: crocodille-erp
          ports:
            - containerPort: 80
              protocol: TCP
