apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: crocodille-erp
  namespace: crocodille-erp
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  rules:
    - http:
      paths:
        - path: /crocodille-erp(/|$)(.*)
          pathType: ImplementationSpecific
          backend:
            service:
              name: crocodille-erp
              port:
                number: 80
