apiVersion: v1
kind: Service
metadata:
  labels:
    name: crocodille-erp
  name: crocodille-erp
  namespace: crocodille-erp
spec:
  selector:
    app: crocodille-erp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
